### ISSUE TITLE
Metapackage

### ISSUE THREAD

**Issue by kossumov** [CIR-KIT-Unit03/cirkit_unit03_pkg#6]
Just another question.

Why do you have an empty cirkit_unit03_pkgs package inside cirkit_unit03_pkgs repository?

I've noticed that you did this a lot. For example inside cirkit_unit03_apps repository, or inside steer_drive_ros.

Thanks

**Comment by MoriKen254** [comment]
here is document http://wiki.ros.org/Metapackages

Is the above one enough?

**Comment by kossumov** [comment]
That's enough.
Thank you

**Comment by MoriKen254** [comment]
ok, I'm happy to hear that
